# Generated by Django 3.1.3 on 2020-11-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcfblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='blog_subtitle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
